# Generated by Django 3.0.5 on 2020-04-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200410_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(related_name='person_unliked', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='api.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostUnlike',
        ),
    ]
