# Generated by Django 3.0.5 on 2020-04-13 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200412_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='person',
        ),
        migrations.AddField(
            model_name='postlike',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_liked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlike',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.Post'),
        ),
    ]
