# Generated by Django 3.0.5 on 2020-04-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200413_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='tweet',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PostLike'),
            preserve_default=False,
        ),
    ]
