# Generated by Django 3.0.5 on 2020-04-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200413_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDislike',
        ),
    ]
