# Generated by Django 3.0.5 on 2020-04-13 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_delete_postdislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='person',
        ),
        migrations.AddField(
            model_name='postlike',
            name='person',
            field=models.ManyToManyField(related_name='person_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
