# Generated by Django 3.0.5 on 2020-04-13 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200413_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='postlike',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='person',
            field=models.ManyToManyField(related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
